apiVersion: v1
kind: Service 
metadata:
  name: my_pod
spec:
  type: Nodeport
  selector:
    app: my_app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
